{% set version = "2.5.2" %}

package:
  name: robotframework-pabot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-pabot/robotframework-pabot-{{ version }}.tar.gz
  sha256: 3fc3f4d34b79c861779625121c6019eccfc4a1ef7f56db0d20b918a415c93d17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - pabot=pabot.pabot:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - robotframework >=3.2
    - robotframework-stacktrace >=0.4.1

test:
  imports:
    - pabot
    - pabot.py3
  commands:
    - python -m pip check
    - pabot --version
    - pabot --help
  requires:
    - pip

about:
  home: https://pabot.org
  summary: Parallel test runner for Robot Framework
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
